# These values are auto-filled in for you
# Don't touch them!
community: yaws-gmodstore
domain: https://yaws-gmodstore.squish.wtf
token: RD1hSAvBmgmXxWTm930CiH0E0vdGQqRd
# These values are auto-filled in for you
# Don't touch them!